global:
  scrape_interval:     5s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: monitoring
    honor_labels: true
    static_configs:
    - targets: ['python-application:5000','nodejs-application:5000']

